<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
  
  <xsl:template match="/">
    <html>
      <head>
        <title>Service Utilization Dashboard</title>
        <link rel="stylesheet" type="text/css" href="style2.css" />
      </head>
      <body>
        <h1>Service Utilization Dashboard</h1>

        <!-- Dashboard Summary -->
        <xsl:variable name="totalServices" select="count(/CarePlatform/Services/Service)"/>
        <xsl:variable name="totalParticipants" select="count(/CarePlatform/Participation/ParticipationEntry)"/>
        
        <!-- Calculate overall utilization rate -->
        <xsl:variable name="totalCapacity" select="$totalServices * 20"/> <!-- Assuming 20 slots per service -->
        <xsl:variable name="overallUtilizationRate" select="($totalParticipants div $totalCapacity) * 100"/>

        <div class="summary">
          <p>Total Services: <xsl:value-of select="$totalServices"/></p>
          <p>Total Participants: <xsl:value-of select="$totalParticipants"/></p>
          <p>Total Capacity: <xsl:value-of select="$totalCapacity"/></p>
          <p>Average Utilization Rate: <xsl:value-of select="format-number($overallUtilizationRate, '0.00')"/>%</p>
        </div>

        <!-- List of Services -->
        <table>
          <thead>
            <tr>
              <th>Service Name</th>
              <th>Type</th>
              <th>Provider</th>
              <th>Location</th>
              <th>Participants</th>
              <th>Total Slots</th>
              <th>Participation Rate</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="/CarePlatform/Services/Service">
              <tr>
                <td><xsl:value-of select="Description"/></td>
                <td><xsl:value-of select="Type"/></td>
                <td>
                  <xsl:value-of select="/CarePlatform/ServiceProviders/Provider[ProviderID=current()/ProviderID]/Name"/>
                </td>
                <td><xsl:value-of select="Location/Address/City"/> - <xsl:value-of select="Location/Room"/></td>

                <!-- Calculate Participants and Capacity -->
                <xsl:variable name="participants" select="count(/CarePlatform/Participation/ParticipationEntry[ServiceID=current()/ID])"/>
                <xsl:variable name="totalSlots" select="20"/> <!-- Fixed capacity example -->
                <td><xsl:value-of select="$participants"/></td>
                <td><xsl:value-of select="$totalSlots"/></td>
                
                <!-- Calculate Participation Rate -->
                <xsl:variable name="participationRate" select="($participants div $totalSlots) * 100"/>
                <td><xsl:value-of select="format-number($participationRate, '0.00')"/>%</td>

                <!-- Determine Status -->
                <xsl:choose>
                  <xsl:when test="$participationRate &lt; 50">
                    <td class="under-utilized">Under-utilized</td>
                  </xsl:when>
                  <xsl:when test="$participationRate &gt;= 90">
                    <td class="high-demand">Fully Booked!</td>
                  </xsl:when>
                  <xsl:otherwise>
                    <td class="normal">Normal Utilization</td>
                  </xsl:otherwise>
                </xsl:choose>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>

        <footer>Generated by CarePlatform Dashboard</footer>
      </body>
    </html>
  </xsl:template>

</xsl:stylesheet>
